// Generated by stubgen from the console's own XNA assemblies.
// Signatures are real; behaviour is not. Do not edit by hand.
#pragma warning disable CS0067, CS0649, CS0108, CS0114, CS0628

namespace Microsoft.Xna.Framework.Storage {
  public partial class StorageContainer : global::System.Object {
  }
  public sealed partial class StorageDevice : global::System.Object {
    public static event global::System.EventHandler<global::System.EventArgs> DeviceChanged { add { } remove { } }
  }
  public partial class StorageDeviceNotConnectedException : global::System.Runtime.InteropServices.ExternalException {
  }
}

