if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed_host_payload.cmake needs -DOUTPUT")
endif()
if(NOT DEFINED VERSION)
  set(VERSION "unversioned")
endif()
if(NOT DEFINED MODE)
  set(MODE "array")
endif()

set(line_pattern "")
foreach(i RANGE 1 32)
  string(APPEND line_pattern "[0-9a-f]")
endforeach()

set(data_body "")
set(entries "")
set(rc_body "")
set(count 0)
if(DEFINED FILES AND NOT FILES STREQUAL "")
  string(REPLACE "," ";" FILES "${FILES}")
  foreach(entry IN LISTS FILES)
    if(entry MATCHES "^([^=]+)=(.+)$")
      set(name "${CMAKE_MATCH_1}")
      set(path "${CMAKE_MATCH_2}")
    else()
      set(name "${entry}")
      set(path "${INPUT_DIR}/${entry}")
    endif()
    if(NOT EXISTS "${path}")
      message(WARNING "Nexia.Xna.Host payload: ${path} does not exist")
      continue()
    endif()
    file(SIZE "${path}" size)
    if(MODE STREQUAL "resource")
      math(EXPR resource_id "29000 + ${count}")
      file(SHA256 "${path}" hash)
      string(APPEND rc_body "// ${name} ${hash}\n")
      string(APPEND rc_body "${resource_id} RCDATA \"${path}\"\n")
      string(APPEND entries
             "    {\"${name}\", nullptr, ${size}, ${resource_id}},\n")
    else()
      file(READ "${path}" hex HEX)
      string(REGEX REPLACE "(${line_pattern})" "\\1\n" hex "${hex}")
      string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
      string(APPEND data_body
             "static const uint8_t kPayload${count}[] = {\n${bytes}0x00};\n\n")
      string(APPEND entries "    {\"${name}\", kPayload${count}, ${size}, 0},\n")
    endif()
    math(EXPR count "${count} + 1")
  endforeach()
endif()

set(body "#include \"xenia/kernel/xna/xna_host_payload.h\"\n\n")
string(APPEND body "namespace xe {\nnamespace kernel {\nnamespace xna {\n\n")
string(APPEND body "const char* const kXnaHostPayloadVersion = \"${VERSION}\";\n\n")
string(APPEND body "${data_body}")
string(APPEND body "const XnaHostPayloadFile kXnaHostPayload[] = {\n")
if(count EQUAL 0)
  string(APPEND body "    {nullptr, nullptr, 0, 0},\n")
else()
  string(APPEND body "${entries}")
endif()
string(APPEND body "};\n")
string(APPEND body "const size_t kXnaHostPayloadCount = ${count};\n\n")
string(APPEND body "}  // namespace xna\n}  // namespace kernel\n}  // namespace xe\n")

set(existing "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL body)
  file(WRITE "${OUTPUT}" "${body}")
endif()

if(DEFINED RC_OUTPUT)
  set(rc_text "// Nexia.Xna.Host ${VERSION}\n${rc_body}")
  set(existing_rc "")
  if(EXISTS "${RC_OUTPUT}")
    file(READ "${RC_OUTPUT}" existing_rc)
  endif()
  if(NOT existing_rc STREQUAL rc_text)
    file(WRITE "${RC_OUTPUT}" "${rc_text}")
  endif()
endif()
