foreach(required INPUT OUTPUT SYMBOL HEADER)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "embed_file.cmake needs -D${required}")
  endif()
endforeach()

set(line_pattern "")
foreach(i RANGE 1 32)
  string(APPEND line_pattern "[0-9a-f]")
endforeach()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_length)
math(EXPR size "${hex_length} / 2")
string(REGEX REPLACE "(${line_pattern})" "\\1\n" hex "${hex}")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")

set(body "#include \"${HEADER}\"\n\n")
string(APPEND body "namespace xe {\nnamespace kernel {\nnamespace xna {\n\n")
string(APPEND body "const uint8_t ${SYMBOL}[] = {\n${bytes}0x00};\n")
string(APPEND body "const size_t ${SYMBOL}Size = ${size};\n\n")
string(APPEND body "}  // namespace xna\n}  // namespace kernel\n}  // namespace xe\n")

set(existing "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL body)
  file(WRITE "${OUTPUT}" "${body}")
endif()
