// Generated by stubgen from the console's own XNA assemblies.
// Signatures are real; behaviour is not. Do not edit by hand.
#pragma warning disable CS0067, CS0649, CS0108, CS0114, CS0628

namespace Microsoft.Xna.Framework.Net {
  public sealed partial class AvailableNetworkSession : global::System.Object {
    public global::System.String HostGamertag { get => default; set { } }
    public global::System.Int32 CurrentGamerCount { get => default; set { } }
    public global::System.Int32 OpenPublicGamerSlots { get => default; set { } }
    public global::System.Int32 OpenPrivateGamerSlots { get => default; set { } }
    private static global::Microsoft.Xna.Framework.Net.NetworkSessionProperties __stub_empty_SessionProperties = new global::Microsoft.Xna.Framework.Net.NetworkSessionProperties();
    public global::Microsoft.Xna.Framework.Net.NetworkSessionProperties SessionProperties { get => __stub_empty_SessionProperties; set { } }
    public global::Microsoft.Xna.Framework.Net.QualityOfService QualityOfService { get => default; set { } }
  }
  public sealed partial class AvailableNetworkSessionCollection : global::System.Collections.ObjectModel.ReadOnlyCollection<global::Microsoft.Xna.Framework.Net.AvailableNetworkSession> {
    public global::System.Boolean IsDisposed { get => default; set { } }
    public void Dispose() { }
  }
  public partial class GameEndedEventArgs : global::System.EventArgs {
    public GameEndedEventArgs() { }
  }
  public partial class GamerJoinedEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.Net.NetworkGamer Gamer { get => default; set { } }
    public GamerJoinedEventArgs(global::Microsoft.Xna.Framework.Net.NetworkGamer gamer) { }
  }
  public partial class GamerLeftEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.Net.NetworkGamer Gamer { get => default; set { } }
    public GamerLeftEventArgs(global::Microsoft.Xna.Framework.Net.NetworkGamer gamer) { }
  }
  public partial class GameStartedEventArgs : global::System.EventArgs {
    public GameStartedEventArgs() { }
  }
  public partial class HostChangedEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.Net.NetworkGamer OldHost { get => default; set { } }
    public global::Microsoft.Xna.Framework.Net.NetworkGamer NewHost { get => default; set { } }
    public HostChangedEventArgs(global::Microsoft.Xna.Framework.Net.NetworkGamer oldHost, global::Microsoft.Xna.Framework.Net.NetworkGamer newHost) { }
  }
  public sealed partial class LocalNetworkGamer : global::Microsoft.Xna.Framework.Net.NetworkGamer {
    public global::Microsoft.Xna.Framework.GamerServices.SignedInGamer SignedInGamer { get => default; set { } }
    public global::System.Boolean IsDataAvailable { get => default; set { } }
    public void EnableSendVoice(global::Microsoft.Xna.Framework.Net.NetworkGamer remoteGamer, global::System.Boolean enable) { }
    public void SendData(global::System.Byte[] data, global::Microsoft.Xna.Framework.Net.SendDataOptions options) { }
    public void SendData(global::System.Byte[] data, global::Microsoft.Xna.Framework.Net.SendDataOptions options, global::Microsoft.Xna.Framework.Net.NetworkGamer recipient) { }
    public void SendData(global::System.Byte[] data, global::System.Int32 offset, global::System.Int32 count, global::Microsoft.Xna.Framework.Net.SendDataOptions options) { }
    public void SendData(global::System.Byte[] data, global::System.Int32 offset, global::System.Int32 count, global::Microsoft.Xna.Framework.Net.SendDataOptions options, global::Microsoft.Xna.Framework.Net.NetworkGamer recipient) { }
    public void SendData(global::Microsoft.Xna.Framework.Net.PacketWriter data, global::Microsoft.Xna.Framework.Net.SendDataOptions options) { }
    public void SendData(global::Microsoft.Xna.Framework.Net.PacketWriter data, global::Microsoft.Xna.Framework.Net.SendDataOptions options, global::Microsoft.Xna.Framework.Net.NetworkGamer recipient) { }
    public global::System.Int32 ReceiveData(global::System.Byte[] data, out global::Microsoft.Xna.Framework.Net.NetworkGamer sender) { sender = default; return default; }
    public global::System.Int32 ReceiveData(global::System.Byte[] data, global::System.Int32 offset, out global::Microsoft.Xna.Framework.Net.NetworkGamer sender) { sender = default; return default; }
    public global::System.Int32 ReceiveData(global::Microsoft.Xna.Framework.Net.PacketReader data, out global::Microsoft.Xna.Framework.Net.NetworkGamer sender) { sender = default; return default; }
    public void SendPartyInvites() { }
  }
  public partial class NetworkGamer : global::Microsoft.Xna.Framework.GamerServices.Gamer {
    public global::Microsoft.Xna.Framework.Net.NetworkSession Session { get => default; set { } }
    public global::Microsoft.Xna.Framework.Net.NetworkMachine Machine { get => default; set { } }
    public global::System.Boolean IsHost { get => default; set { } }
    public global::System.Boolean IsLocal { get => default; set { } }
    public global::System.Boolean IsPrivateSlot { get => default; set { } }
    public global::System.Boolean IsReady { get => default; set { } }
    public global::System.Boolean HasVoice { get => default; set { } }
    public global::System.Boolean IsTalking { get => default; set { } }
    public global::System.Boolean IsMutedByLocalUser { get => default; set { } }
    public global::System.Boolean IsGuest { get => default; set { } }
    public global::System.TimeSpan RoundtripTime { get => default; set { } }
    public global::System.Byte Id { get => default; set { } }
    public global::System.Boolean HasLeftSession { get => default; set { } }
  }
  public sealed partial class NetworkMachine : global::System.Object {
    private static global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> __stub_empty_Gamers = new global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer>();
    public global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> Gamers { get => __stub_empty_Gamers; set { } }
    public void RemoveFromSession() { }
  }
  public sealed partial class NetworkSession : global::System.Object {
    public static global::System.Int32 MaxSupportedGamers;
    public static global::System.Int32 MaxPreviousGamers;
    public global::System.Boolean IsDisposed { get => default; set { } }
    public global::Microsoft.Xna.Framework.Net.NetworkSessionType SessionType { get => default; set { } }
    public global::Microsoft.Xna.Framework.Net.NetworkSessionState SessionState { get => default; set { } }
    public global::System.Boolean IsHost { get => default; set { } }
    public global::Microsoft.Xna.Framework.Net.NetworkGamer Host { get => default; set { } }
    private static global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> __stub_empty_AllGamers = new global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer>();
    public global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> AllGamers { get => __stub_empty_AllGamers; set { } }
    private static global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.LocalNetworkGamer> __stub_empty_LocalGamers = new global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.LocalNetworkGamer>();
    public global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.LocalNetworkGamer> LocalGamers { get => __stub_empty_LocalGamers; set { } }
    private static global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> __stub_empty_RemoteGamers = new global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer>();
    public global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> RemoteGamers { get => __stub_empty_RemoteGamers; set { } }
    private static global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> __stub_empty_PreviousGamers = new global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer>();
    public global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.Net.NetworkGamer> PreviousGamers { get => __stub_empty_PreviousGamers; set { } }
    public global::System.Boolean IsEveryoneReady { get => default; set { } }
    public global::System.Int32 MaxGamers { get => default; set { } }
    public global::System.Int32 PrivateGamerSlots { get => default; set { } }
    public global::System.Single SimulatedPacketLoss { get => default; set { } }
    public global::System.TimeSpan SimulatedLatency { get => default; set { } }
    public global::System.Int32 BytesPerSecondSent { get => default; set { } }
    public global::System.Int32 BytesPerSecondReceived { get => default; set { } }
    private static global::Microsoft.Xna.Framework.Net.NetworkSessionProperties __stub_empty_SessionProperties = new global::Microsoft.Xna.Framework.Net.NetworkSessionProperties();
    public global::Microsoft.Xna.Framework.Net.NetworkSessionProperties SessionProperties { get => __stub_empty_SessionProperties; set { } }
    public global::System.Boolean AllowJoinInProgress { get => default; set { } }
    public global::System.Boolean AllowHostMigration { get => default; set { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.NetworkSessionEndedEventArgs> SessionEnded { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.GamerJoinedEventArgs> GamerJoined { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.GamerLeftEventArgs> GamerLeft { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.GameStartedEventArgs> GameStarted { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.GameEndedEventArgs> GameEnded { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.HostChangedEventArgs> HostChanged { add { } remove { } }
    public static event global::System.EventHandler<global::Microsoft.Xna.Framework.GamerServices.InviteAcceptedEventArgs> InviteAccepted { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.WriteLeaderboardsEventArgs> WriteArbitratedLeaderboard { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.WriteLeaderboardsEventArgs> WriteTrueSkill { add { } remove { } }
    public event global::System.EventHandler<global::Microsoft.Xna.Framework.Net.WriteLeaderboardsEventArgs> WriteUnarbitratedLeaderboard { add { } remove { } }
    public static global::Microsoft.Xna.Framework.Net.NetworkSession Create(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Int32 maxLocalGamers, global::System.Int32 maxGamers) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession Create(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Int32 maxLocalGamers, global::System.Int32 maxGamers, global::System.Int32 privateGamerSlots, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties sessionProperties) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession Create(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> localGamers, global::System.Int32 maxGamers, global::System.Int32 privateGamerSlots, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties sessionProperties) => default;
    public static global::System.IAsyncResult BeginCreate(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Int32 maxLocalGamers, global::System.Int32 maxGamers, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.IAsyncResult BeginCreate(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Int32 maxLocalGamers, global::System.Int32 maxGamers, global::System.Int32 privateGamerSlots, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties sessionProperties, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.IAsyncResult BeginCreate(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> localGamers, global::System.Int32 maxGamers, global::System.Int32 privateGamerSlots, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties sessionProperties, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession EndCreate(global::System.IAsyncResult result) => default;
    public static global::Microsoft.Xna.Framework.Net.AvailableNetworkSessionCollection Find(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Int32 maxLocalGamers, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties searchProperties) => new global::Microsoft.Xna.Framework.Net.AvailableNetworkSessionCollection();
    public static global::Microsoft.Xna.Framework.Net.AvailableNetworkSessionCollection Find(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> localGamers, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties searchProperties) => new global::Microsoft.Xna.Framework.Net.AvailableNetworkSessionCollection();
    public static global::System.IAsyncResult BeginFind(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Int32 maxLocalGamers, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties searchProperties, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.IAsyncResult BeginFind(global::Microsoft.Xna.Framework.Net.NetworkSessionType sessionType, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> localGamers, global::Microsoft.Xna.Framework.Net.NetworkSessionProperties searchProperties, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::Microsoft.Xna.Framework.Net.AvailableNetworkSessionCollection EndFind(global::System.IAsyncResult result) => new global::Microsoft.Xna.Framework.Net.AvailableNetworkSessionCollection();
    public static global::Microsoft.Xna.Framework.Net.NetworkSession Join(global::Microsoft.Xna.Framework.Net.AvailableNetworkSession availableSession) => default;
    public static global::System.IAsyncResult BeginJoin(global::Microsoft.Xna.Framework.Net.AvailableNetworkSession availableSession, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession EndJoin(global::System.IAsyncResult result) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession JoinInvited(global::System.Int32 maxLocalGamers) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession JoinInvited(global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> localGamers) => default;
    public static global::System.IAsyncResult BeginJoinInvited(global::System.Int32 maxLocalGamers, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.IAsyncResult BeginJoinInvited(global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> localGamers, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::Microsoft.Xna.Framework.Net.NetworkSession EndJoinInvited(global::System.IAsyncResult result) => default;
    public void Dispose() { }
    public void Update() { }
    public void StartGame() { }
    public void EndGame() { }
    public void ResetReady() { }
    public global::Microsoft.Xna.Framework.Net.NetworkGamer FindGamerById(global::System.Byte gamerId) => default;
    public void AddLocalGamer(global::Microsoft.Xna.Framework.GamerServices.SignedInGamer gamer) { }
  }
  public partial class NetworkSessionEndedEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.Net.NetworkSessionEndReason EndReason { get => default; set { } }
    public NetworkSessionEndedEventArgs(global::Microsoft.Xna.Framework.Net.NetworkSessionEndReason endReason) { }
  }
  public enum NetworkSessionEndReason : int {
    ClientSignedOut = 0,
    HostEndedSession = 1,
    RemovedByHost = 2,
    Disconnected = 3,
  }
  public enum NetworkSessionJoinError : int {
    SessionNotFound = 0,
    SessionNotJoinable = 1,
    SessionFull = 2,
  }
  public partial class NetworkSessionJoinException : global::Microsoft.Xna.Framework.GamerServices.NetworkException {
    public global::Microsoft.Xna.Framework.Net.NetworkSessionJoinError JoinError { get => default; set { } }
    public NetworkSessionJoinException() { }
    public NetworkSessionJoinException(global::System.String message) { }
    public NetworkSessionJoinException(global::System.String message, global::Microsoft.Xna.Framework.Net.NetworkSessionJoinError joinError) { }
    public NetworkSessionJoinException(global::System.String message, global::System.Exception innerException) { }
  }
  public partial class NetworkSessionProperties : global::System.Object {
    public global::System.Int32 Count { get => default; set { } }
    public NetworkSessionProperties() { }
    public global::System.Collections.Generic.IEnumerator<global::System.Nullable<global::System.Int32>> GetEnumerator() => default;
  }
  public enum NetworkSessionState : int {
    Lobby = 0,
    Playing = 1,
    Ended = 2,
  }
  public enum NetworkSessionType : int {
    Local = 0,
    SystemLink = 1,
    PlayerMatch = 2,
    Ranked = 3,
    LocalWithLeaderboards = 4,
  }
  public partial class PacketReader : global::System.IO.BinaryReader {
    public global::System.Int32 Length { get => default; set { } }
    public global::System.Int32 Position { get => default; set { } }
    public global::Microsoft.Xna.Framework.Vector2 ReadVector2() => default;
    public global::Microsoft.Xna.Framework.Vector3 ReadVector3() => default;
    public global::Microsoft.Xna.Framework.Vector4 ReadVector4() => default;
    public global::Microsoft.Xna.Framework.Matrix ReadMatrix() => default;
    public global::Microsoft.Xna.Framework.Quaternion ReadQuaternion() => default;
    public global::Microsoft.Xna.Framework.Color ReadColor() => default;
    public virtual global::System.Single ReadSingle() => default;
    public virtual global::System.Double ReadDouble() => default;
  }
  public partial class PacketWriter : global::System.IO.BinaryWriter {
    public global::System.Int32 Length { get => default; set { } }
    public global::System.Int32 Position { get => default; set { } }
    public PacketWriter() { }
    public PacketWriter(global::System.Int32 capacity) { }
    public void Write(global::Microsoft.Xna.Framework.Vector2 @value) { }
    public void Write(global::Microsoft.Xna.Framework.Vector3 @value) { }
    public void Write(global::Microsoft.Xna.Framework.Vector4 @value) { }
    public void Write(global::Microsoft.Xna.Framework.Matrix @value) { }
    public void Write(global::Microsoft.Xna.Framework.Quaternion @value) { }
    public void Write(global::Microsoft.Xna.Framework.Color @value) { }
    public virtual void Write(global::System.Single @value) { }
    public virtual void Write(global::System.Double @value) { }
  }
  public sealed partial class QualityOfService : global::System.Object {
    public global::System.Boolean IsAvailable { get => default; set { } }
    public global::System.Int32 BytesPerSecondUpstream { get => default; set { } }
    public global::System.Int32 BytesPerSecondDownstream { get => default; set { } }
    public global::System.TimeSpan AverageRoundtripTime { get => default; set { } }
    public global::System.TimeSpan MinimumRoundtripTime { get => default; set { } }
  }
  public enum SendDataOptions : int {
    None = 0,
    Reliable = 1,
    InOrder = 2,
    ReliableInOrder = 3,
    Chat = 4,
  }
  public sealed partial class WriteLeaderboardsEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.Net.NetworkGamer Gamer { get => default; set { } }
    public global::System.Boolean IsLeaving { get => default; set { } }
  }
}

