// Generated by stubgen from the console's own XNA assemblies.
// Signatures are real; behaviour is not. Do not edit by hand.
#pragma warning disable CS0067, CS0649, CS0108, CS0114, CS0628

namespace Microsoft.Xna.Framework.GamerServices {
  public partial class AvatarAnimation : global::System.Object {
    public global::System.TimeSpan Length { get => default; set { } }
    public global::System.TimeSpan CurrentPosition { get => default; set { } }
    public global::System.Collections.ObjectModel.ReadOnlyCollection<global::Microsoft.Xna.Framework.Matrix> BoneTransforms { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarExpression Expression { get => default; set { } }
    public global::System.Boolean IsDisposed { get => default; set { } }
    public AvatarAnimation(global::Microsoft.Xna.Framework.GamerServices.AvatarAnimationPreset animationPreset) { }
    public void Update(global::System.TimeSpan elapsedAnimationTime, global::System.Boolean loop) { }
    public void Dispose() { }
    protected virtual void Dispose(global::System.Boolean disposing) { }
  }
  public enum AvatarAnimationPreset : int {
    Stand0 = 0,
    Stand1 = 1,
    Stand2 = 2,
    Stand3 = 3,
    Stand4 = 4,
    Stand5 = 5,
    Stand6 = 6,
    Stand7 = 7,
    Clap = 8,
    Wave = 9,
    Celebrate = 10,
    FemaleIdleCheckNails = 11,
    FemaleIdleLookAround = 12,
    FemaleIdleShiftWeight = 13,
    FemaleIdleFixShoe = 14,
    FemaleAngry = 15,
    FemaleConfused = 16,
    FemaleLaugh = 17,
    FemaleCry = 18,
    FemaleShocked = 19,
    FemaleYawn = 20,
    MaleIdleLookAround = 21,
    MaleIdleStretch = 22,
    MaleIdleShiftWeight = 23,
    MaleIdleCheckHand = 24,
    MaleAngry = 25,
    MaleConfused = 26,
    MaleLaugh = 27,
    MaleCry = 28,
    MaleSurprised = 29,
    MaleYawn = 30,
  }
  public enum AvatarBodyType : int {
    Female = 0,
    Male = 1,
  }
  public enum AvatarBone : int {
    Root = 0,
    BackLower = 1,
    HipLeft = 2,
    HipRight = 3,
    BackUpper = 5,
    KneeLeft = 6,
    KneeRight = 8,
    AnkleLeft = 11,
    CollarLeft = 12,
    Neck = 14,
    AnkleRight = 15,
    CollarRight = 16,
    Head = 19,
    ShoulderLeft = 20,
    ToeLeft = 21,
    ShoulderRight = 22,
    ToeRight = 23,
    ElbowLeft = 25,
    ElbowRight = 28,
    WristLeft = 33,
    WristRight = 36,
    FingerIndexLeft = 37,
    FingerMiddleLeft = 38,
    FingerRingLeft = 39,
    FingerSmallLeft = 40,
    PropLeft = 41,
    SpecialLeft = 42,
    FingerThumbLeft = 43,
    FingerIndexRight = 44,
    FingerMiddleRight = 45,
    FingerRingRight = 46,
    FingerSmallRight = 47,
    PropRight = 48,
    SpecialRight = 49,
    FingerThumbRight = 50,
    FingerIndex2Left = 51,
    FingerMiddle2Left = 52,
    FingerRing2Left = 53,
    FingerSmall2Left = 54,
    FingerThumb2Left = 55,
    FingerIndex2Right = 56,
    FingerMiddle2Right = 57,
    FingerRing2Right = 58,
    FingerSmall2Right = 59,
    FingerThumb2Right = 60,
    FingerIndex3Left = 61,
    FingerMiddle3Left = 62,
    FingerRing3Left = 63,
    FingerSmall3Left = 64,
    FingerThumb3Left = 65,
    FingerIndex3Right = 66,
    FingerMiddle3Right = 67,
    FingerRing3Right = 68,
    FingerSmall3Right = 69,
    FingerThumb3Right = 70,
  }
  public partial class AvatarDescription : global::System.Object {
    public global::System.Boolean IsValid { get => default; set { } }
    private static global::System.Byte[] __stub_empty_Description = global::System.Array.Empty<global::System.Byte>();
    public global::System.Byte[] Description { get => __stub_empty_Description; set { } }
    public global::System.Single Height { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarBodyType BodyType { get => default; set { } }
    public event global::System.EventHandler<global::System.EventArgs> Changed { add { } remove { } }
    public AvatarDescription(global::System.Byte[] data) { }
    public static global::System.IAsyncResult BeginGetFromGamer(global::Microsoft.Xna.Framework.GamerServices.Gamer gamer, global::System.AsyncCallback callback, global::System.Object state) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.AvatarDescription EndGetFromGamer(global::System.IAsyncResult result) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.AvatarDescription CreateRandom() => default;
    public static global::Microsoft.Xna.Framework.GamerServices.AvatarDescription CreateRandom(global::Microsoft.Xna.Framework.GamerServices.AvatarBodyType bodyType) => default;
  }
  public partial struct AvatarExpression {
    public global::Microsoft.Xna.Framework.GamerServices.AvatarMouth Mouth { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarEye LeftEye { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarEye RightEye { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarEyebrow LeftEyebrow { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarEyebrow RightEyebrow { get => default; set { } }
  }
  public enum AvatarEye : int {
    Neutral = 0,
    Sad = 1,
    Angry = 2,
    Confused = 3,
    Laughing = 4,
    Shocked = 5,
    Happy = 6,
    Yawning = 7,
    Sleeping = 8,
    LookUp = 9,
    LookDown = 10,
    LookLeft = 11,
    LookRight = 12,
    Blink = 13,
  }
  public enum AvatarEyebrow : int {
    Neutral = 0,
    Sad = 1,
    Angry = 2,
    Confused = 3,
    Raised = 4,
  }
  public enum AvatarMouth : int {
    Neutral = 0,
    Sad = 1,
    Angry = 2,
    Confused = 3,
    Laughing = 4,
    Shocked = 5,
    Happy = 6,
    PhoneticO = 7,
    PhoneticAi = 8,
    PhoneticEe = 9,
    PhoneticFv = 10,
    PhoneticW = 11,
    PhoneticL = 12,
    PhoneticDth = 13,
  }
  public partial class AvatarRenderer : global::System.Object {
    public static global::System.Int32 BoneCount;
    public global::Microsoft.Xna.Framework.Matrix World { get => default; set { } }
    public global::Microsoft.Xna.Framework.Matrix View { get => default; set { } }
    public global::Microsoft.Xna.Framework.Matrix Projection { get => default; set { } }
    public global::System.Collections.ObjectModel.ReadOnlyCollection<global::System.Int32> ParentBones { get => default; set { } }
    public global::System.Collections.ObjectModel.ReadOnlyCollection<global::Microsoft.Xna.Framework.Matrix> BindPose { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarRendererState State { get => default; set { } }
    public global::Microsoft.Xna.Framework.Vector3 LightColor { get => default; set { } }
    public global::Microsoft.Xna.Framework.Vector3 LightDirection { get => default; set { } }
    public global::Microsoft.Xna.Framework.Vector3 AmbientLightColor { get => default; set { } }
    public global::System.Boolean IsDisposed { get => default; set { } }
    public AvatarRenderer(global::Microsoft.Xna.Framework.GamerServices.AvatarDescription avatarDescription) { }
    public AvatarRenderer(global::Microsoft.Xna.Framework.GamerServices.AvatarDescription avatarDescription, global::System.Boolean useLoadingEffect) { }
    public void Draw(global::Microsoft.Xna.Framework.GamerServices.IAvatarAnimation animation) { }
    public void Draw(global::System.Collections.Generic.IList<global::Microsoft.Xna.Framework.Matrix> bones, global::Microsoft.Xna.Framework.GamerServices.AvatarExpression expression) { }
    public void Dispose() { }
    protected virtual void Dispose(global::System.Boolean disposing) { }
  }
  public enum AvatarRendererState : int {
    Loading = 0,
    Ready = 1,
    Unavailable = 2,
  }
  public partial interface IAvatarAnimation {
    public global::System.Collections.ObjectModel.ReadOnlyCollection<global::Microsoft.Xna.Framework.Matrix> BoneTransforms { get; set; }
    public global::System.TimeSpan CurrentPosition { get; set; }
    public global::System.TimeSpan Length { get; set; }
    public global::Microsoft.Xna.Framework.GamerServices.AvatarExpression Expression { get; set; }
    void Update(global::System.TimeSpan elapsedAnimationTime, global::System.Boolean loop);
  }
}

