// Generated by stubgen from the console's own XNA assemblies.
// Signatures are real; behaviour is not. Do not edit by hand.
#pragma warning disable CS0067, CS0649, CS0108, CS0114, CS0628

namespace Microsoft.Xna.Framework.GamerServices {
  public sealed partial class Achievement : global::System.Object {
    public global::System.String Key { get => default; set { } }
    public global::System.String Name { get => default; set { } }
    public global::System.String Description { get => default; set { } }
    public global::System.String HowToEarn { get => default; set { } }
    public global::System.Int32 GamerScore { get => default; set { } }
    public global::System.Boolean IsEarned { get => default; set { } }
    public global::System.Boolean EarnedOnline { get => default; set { } }
    public global::System.Boolean DisplayBeforeEarned { get => default; set { } }
    public global::System.DateTime EarnedDateTime { get => default; set { } }
    public global::System.IO.Stream GetPicture() => default;
  }
  public sealed partial class AchievementCollection : global::System.Object {
    public global::System.Boolean IsDisposed { get => default; set { } }
    public global::System.Int32 Count { get => default; set { } }
    public void Dispose() { }
    public global::System.Collections.Generic.IEnumerator<global::Microsoft.Xna.Framework.GamerServices.Achievement> GetEnumerator() => default;
  }
  public enum ControllerSensitivity : int {
    Low = 0,
    Medium = 1,
    High = 2,
  }
  public sealed partial class FriendCollection : global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.GamerServices.FriendGamer> {
    public global::System.Boolean IsDisposed { get => default; set { } }
    public void Dispose() { }
  }
  public sealed partial class FriendGamer : global::Microsoft.Xna.Framework.GamerServices.Gamer {
    public global::System.String Presence { get => default; set { } }
    public global::System.Boolean IsOnline { get => default; set { } }
    public global::System.Boolean IsPlaying { get => default; set { } }
    public global::System.Boolean IsJoinable { get => default; set { } }
    public global::System.Boolean IsAway { get => default; set { } }
    public global::System.Boolean IsBusy { get => default; set { } }
    public global::System.Boolean HasVoice { get => default; set { } }
    public global::System.Boolean FriendRequestReceivedFrom { get => default; set { } }
    public global::System.Boolean FriendRequestSentTo { get => default; set { } }
    public global::System.Boolean InviteReceivedFrom { get => default; set { } }
    public global::System.Boolean InviteSentTo { get => default; set { } }
    public global::System.Boolean InviteAccepted { get => default; set { } }
    public global::System.Boolean InviteRejected { get => default; set { } }
  }
  public sealed partial class GameDefaults : global::System.Object {
    public global::Microsoft.Xna.Framework.GamerServices.GameDifficulty GameDifficulty { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.ControllerSensitivity ControllerSensitivity { get => default; set { } }
    public global::System.Nullable<global::Microsoft.Xna.Framework.Color> PrimaryColor { get => default; set { } }
    public global::System.Nullable<global::Microsoft.Xna.Framework.Color> SecondaryColor { get => default; set { } }
    public global::System.Boolean AutoAim { get => default; set { } }
    public global::System.Boolean AutoCenter { get => default; set { } }
    public global::System.Boolean MoveWithRightThumbStick { get => default; set { } }
    public global::System.Boolean InvertYAxis { get => default; set { } }
    public global::System.Boolean ManualTransmission { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.RacingCameraAngle RacingCameraAngle { get => default; set { } }
    public global::System.Boolean AccelerateWithButtons { get => default; set { } }
    public global::System.Boolean BrakeWithButtons { get => default; set { } }
  }
  public enum GameDifficulty : int {
    Easy = 0,
    Normal = 1,
    Hard = 2,
  }
  public abstract partial class Gamer : global::System.Object {
    public global::System.Boolean IsDisposed { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.LeaderboardWriter LeaderboardWriter { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerProfile GetProfile() => default;
    public global::System.IAsyncResult BeginGetProfile(global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public global::Microsoft.Xna.Framework.GamerServices.GamerProfile EndGetProfile(global::System.IAsyncResult result) => default;
    public static global::System.IAsyncResult BeginGetFromGamertag(global::System.String gamertag, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.Gamer EndGetFromGamertag(global::System.IAsyncResult result) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.Gamer GetFromGamertag(global::System.String gamertag) => default;
    public static global::System.IAsyncResult BeginGetPartnerToken(global::System.String audienceUri, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.String EndGetPartnerToken(global::System.IAsyncResult result) => default;
    public static global::System.String GetPartnerToken(global::System.String audienceUri) => default;
  }
  public partial class GamerCollection<T> : global::System.Collections.ObjectModel.ReadOnlyCollection<T> {
  }
  public sealed partial class GamerPresence : global::System.Object {
    public global::Microsoft.Xna.Framework.GamerServices.GamerPresenceMode PresenceMode { get => default; set { } }
    public global::System.Int32 PresenceValue { get => default; set { } }
  }
  public enum GamerPresenceMode : int {
    None = 0,
    SinglePlayer = 1,
    Multiplayer = 2,
    LocalCoOp = 3,
    LocalVersus = 4,
    OnlineCoOp = 5,
    OnlineVersus = 6,
    VersusComputer = 7,
    Stage = 8,
    Level = 9,
    CoOpStage = 10,
    CoOpLevel = 11,
    ArcadeMode = 12,
    CampaignMode = 13,
    ChallengeMode = 14,
    ExplorationMode = 15,
    PracticeMode = 16,
    PuzzleMode = 17,
    ScenarioMode = 18,
    StoryMode = 19,
    SurvivalMode = 20,
    TutorialMode = 21,
    DifficultyEasy = 22,
    DifficultyMedium = 23,
    DifficultyHard = 24,
    DifficultyExtreme = 25,
    Score = 26,
    VersusScore = 27,
    Winning = 28,
    Losing = 29,
    ScoreIsTied = 30,
    Outnumbered = 31,
    OnARoll = 32,
    InCombat = 33,
    BattlingBoss = 34,
    TimeAttack = 35,
    TryingForRecord = 36,
    FreePlay = 37,
    WastingTime = 38,
    StuckOnAHardBit = 39,
    NearlyFinished = 40,
    LookingForGames = 41,
    WaitingForPlayers = 42,
    WaitingInLobby = 43,
    SettingUpMatch = 44,
    PlayingWithFriends = 45,
    AtMenu = 46,
    StartingGame = 47,
    Paused = 48,
    GameOver = 49,
    WonTheGame = 50,
    ConfiguringSettings = 51,
    CustomizingPlayer = 52,
    EditingLevel = 53,
    InGameStore = 54,
    WatchingCutscene = 55,
    WatchingCredits = 56,
    PlayingMinigame = 57,
    FoundSecret = 58,
    CornflowerBlue = 59,
  }
  public partial class GamerPrivilegeException : global::System.Exception {
    public GamerPrivilegeException() { }
    public GamerPrivilegeException(global::System.String message) { }
    public GamerPrivilegeException(global::System.String message, global::System.Exception innerException) { }
  }
  public sealed partial class GamerPrivileges : global::System.Object {
    public global::System.Boolean AllowOnlineSessions { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerPrivilegeSetting AllowCommunication { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerPrivilegeSetting AllowProfileViewing { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerPrivilegeSetting AllowUserCreatedContent { get => default; set { } }
    public global::System.Boolean AllowTradeContent { get => default; set { } }
    public global::System.Boolean AllowPurchaseContent { get => default; set { } }
    public global::System.Boolean AllowPremiumContent { get => default; set { } }
  }
  public enum GamerPrivilegeSetting : int {
    Blocked = 0,
    FriendsOnly = 1,
    Everyone = 2,
  }
  public sealed partial class GamerProfile : global::System.Object {
    public global::System.Boolean IsDisposed { get => default; set { } }
    public global::System.String Motto { get => default; set { } }
    public global::System.Single Reputation { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerZone GamerZone { get => default; set { } }
    public global::System.Globalization.RegionInfo Region { get => default; set { } }
    public global::System.Int32 GamerScore { get => default; set { } }
    public global::System.Int32 TitlesPlayed { get => default; set { } }
    public global::System.Int32 TotalAchievements { get => default; set { } }
    public void Dispose() { }
    public global::System.IO.Stream GetGamerPicture() => default;
  }
  public sealed partial class GamerServicesDispatcher : global::System.Object {
    public static global::System.IntPtr WindowHandle { get => default; set { } }
    public static global::System.Boolean IsInitialized { get => default; set { } }
    public static event global::System.EventHandler<global::System.EventArgs> InstallingTitleUpdate { add { } remove { } }
    public static void Initialize(global::System.IServiceProvider serviceProvider) { }
    public static void Update() { }
  }
  public partial class GamerServicesNotAvailableException : global::System.Exception {
    public GamerServicesNotAvailableException() { }
    public GamerServicesNotAvailableException(global::System.String message) { }
    public GamerServicesNotAvailableException(global::System.String message, global::System.Exception innerException) { }
  }
  public enum GamerZone : int {
    Unknown = 0,
    Recreation = 1,
    Pro = 2,
    Family = 3,
    Underground = 4,
  }
  public partial class GameUpdateRequiredException : global::System.Exception {
    public GameUpdateRequiredException() { }
    public GameUpdateRequiredException(global::System.String message) { }
    public GameUpdateRequiredException(global::System.String message, global::System.Exception innerException) { }
  }
  public sealed partial class Guide : global::System.Object {
    public static global::Microsoft.Xna.Framework.GamerServices.NotificationPosition NotificationPosition { get => default; set { } }
    public static global::System.Boolean IsScreenSaverEnabled { get => default; set { } }
    public static void ShowSignIn(global::System.Int32 paneCount, global::System.Boolean onlineOnly) { }
    public static void ShowMessages(global::Microsoft.Xna.Framework.PlayerIndex player) { }
    public static void ShowFriends(global::Microsoft.Xna.Framework.PlayerIndex player) { }
    public static void ShowPlayers(global::Microsoft.Xna.Framework.PlayerIndex player) { }
    public static void ShowFriendRequest(global::Microsoft.Xna.Framework.PlayerIndex player, global::Microsoft.Xna.Framework.GamerServices.Gamer gamer) { }
    public static void ShowPlayerReview(global::Microsoft.Xna.Framework.PlayerIndex player, global::Microsoft.Xna.Framework.GamerServices.Gamer gamer) { }
    public static void ShowGamerCard(global::Microsoft.Xna.Framework.PlayerIndex player, global::Microsoft.Xna.Framework.GamerServices.Gamer gamer) { }
    public static void ShowParty(global::Microsoft.Xna.Framework.PlayerIndex player) { }
    public static void ShowPartySessions(global::Microsoft.Xna.Framework.PlayerIndex player) { }
    public static void ShowComposeMessage(global::Microsoft.Xna.Framework.PlayerIndex player, global::System.String text, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.Gamer> recipients) { }
    public static void DelayNotifications(global::System.TimeSpan delay) { }
    public static void ShowGameInvite(global::Microsoft.Xna.Framework.PlayerIndex player, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.Gamer> recipients) { }
    public static void ShowGameInvite(global::System.String sessionId) { }
    public static void ShowMarketplace(global::Microsoft.Xna.Framework.PlayerIndex player) { }
  }
  public partial class GuideAlreadyVisibleException : global::System.Exception {
    public GuideAlreadyVisibleException() { }
    public GuideAlreadyVisibleException(global::System.String message) { }
    public GuideAlreadyVisibleException(global::System.String message, global::System.Exception innerException) { }
  }
  public partial class InviteAcceptedEventArgs : global::System.EventArgs {
    public global::System.Boolean IsCurrentSession { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.SignedInGamer Gamer { get => default; set { } }
    public InviteAcceptedEventArgs(global::Microsoft.Xna.Framework.GamerServices.SignedInGamer gamer, global::System.Boolean isCurrentSession) { }
  }
  public sealed partial class LeaderboardEntry : global::System.Object {
    public global::Microsoft.Xna.Framework.GamerServices.Gamer Gamer { get => default; set { } }
    public global::System.Int64 Rating { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.PropertyDictionary Columns { get => default; set { } }
  }
  public partial struct LeaderboardIdentity {
    public global::System.String Key { get => default; set { } }
    public global::System.Int32 GameMode { get => default; set { } }
    public static global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity Create(global::Microsoft.Xna.Framework.GamerServices.LeaderboardKey key, global::System.Int32 gameMode) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity Create(global::Microsoft.Xna.Framework.GamerServices.LeaderboardKey key) => default;
  }
  public enum LeaderboardKey : int {
    BestScoreLifeTime = 0,
    BestScoreRecent = 1,
    BestTimeLifeTime = 2,
    BestTimeRecent = 3,
  }
  public enum LeaderboardOutcome : int {
    None = 0,
    Win = 1,
    Loss = 2,
    Tie = 3,
  }
  public sealed partial class LeaderboardReader : global::System.Object {
    public global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity LeaderboardIdentity { get => default; set { } }
    public global::System.Int32 TotalLeaderboardSize { get => default; set { } }
    public global::System.Int32 PageStart { get => default; set { } }
    public global::System.Collections.ObjectModel.ReadOnlyCollection<global::Microsoft.Xna.Framework.GamerServices.LeaderboardEntry> Entries { get => default; set { } }
    public global::System.Boolean IsDisposed { get => default; set { } }
    public global::System.Boolean CanPageUp { get => default; set { } }
    public global::System.Boolean CanPageDown { get => default; set { } }
    public static global::Microsoft.Xna.Framework.GamerServices.LeaderboardReader Read(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.Gamer> gamers, global::Microsoft.Xna.Framework.GamerServices.Gamer pivotGamer, global::System.Int32 pageSize) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.LeaderboardReader Read(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId, global::Microsoft.Xna.Framework.GamerServices.Gamer pivotGamer, global::System.Int32 pageSize) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.LeaderboardReader Read(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId, global::System.Int32 pageStart, global::System.Int32 pageSize) => default;
    public static global::System.IAsyncResult BeginRead(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId, global::System.Collections.Generic.IEnumerable<global::Microsoft.Xna.Framework.GamerServices.Gamer> gamers, global::Microsoft.Xna.Framework.GamerServices.Gamer pivotGamer, global::System.Int32 pageSize, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.IAsyncResult BeginRead(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId, global::Microsoft.Xna.Framework.GamerServices.Gamer pivotGamer, global::System.Int32 pageSize, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::System.IAsyncResult BeginRead(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId, global::System.Int32 pageStart, global::System.Int32 pageSize, global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public static global::Microsoft.Xna.Framework.GamerServices.LeaderboardReader EndRead(global::System.IAsyncResult result) => default;
    public void Dispose() { }
    public void PageUp() { }
    public void PageDown() { }
    public global::System.IAsyncResult BeginPageUp(global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public global::System.IAsyncResult BeginPageDown(global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public void EndPageUp(global::System.IAsyncResult result) { }
    public void EndPageDown(global::System.IAsyncResult result) { }
  }
  public sealed partial class LeaderboardWriter : global::System.Object {
    public LeaderboardWriter() { }
    public global::Microsoft.Xna.Framework.GamerServices.LeaderboardEntry GetLeaderboard(global::Microsoft.Xna.Framework.GamerServices.LeaderboardIdentity leaderboardId) => default;
  }
  public enum MessageBoxIcon : int {
    None = 0,
    Error = 1,
    Warning = 2,
    Alert = 3,
  }
  public partial class NetworkException : global::System.Exception {
    public NetworkException() { }
    public NetworkException(global::System.String message) { }
    public NetworkException(global::System.String message, global::System.Exception innerException) { }
  }
  public partial class NetworkNotAvailableException : global::Microsoft.Xna.Framework.GamerServices.NetworkException {
    public NetworkNotAvailableException() { }
    public NetworkNotAvailableException(global::System.String message) { }
    public NetworkNotAvailableException(global::System.String message, global::System.Exception innerException) { }
  }
  public enum NotificationPosition : int {
    TopLeft = 0,
    TopCenter = 1,
    TopRight = 2,
    CenterLeft = 3,
    Center = 4,
    CenterRight = 5,
    BottomLeft = 6,
    BottomCenter = 7,
    BottomRight = 8,
  }
  public sealed partial class PropertyDictionary : global::System.Object {
    public global::System.Int32 Count { get => default; set { } }
    public global::System.Int32 GetValueInt32(global::System.String key) => default;
    public global::System.Int64 GetValueInt64(global::System.String key) => default;
    public global::System.Single GetValueSingle(global::System.String key) => default;
    public global::System.Double GetValueDouble(global::System.String key) => default;
    public global::System.String GetValueString(global::System.String key) => default;
    public global::Microsoft.Xna.Framework.GamerServices.LeaderboardOutcome GetValueOutcome(global::System.String key) => default;
    public global::System.DateTime GetValueDateTime(global::System.String key) => default;
    public global::System.TimeSpan GetValueTimeSpan(global::System.String key) => default;
    public global::System.IO.Stream GetValueStream(global::System.String key) => default;
    public void SetValue(global::System.String key, global::System.Int32 @value) { }
    public void SetValue(global::System.String key, global::System.Int64 @value) { }
    public void SetValue(global::System.String key, global::System.Single @value) { }
    public void SetValue(global::System.String key, global::System.Double @value) { }
    public void SetValue(global::System.String key, global::System.String @value) { }
    public void SetValue(global::System.String key, global::Microsoft.Xna.Framework.GamerServices.LeaderboardOutcome @value) { }
    public void SetValue(global::System.String key, global::System.DateTime @value) { }
    public void SetValue(global::System.String key, global::System.TimeSpan @value) { }
    public global::System.Boolean ContainsKey(global::System.String key) => default;
    public global::System.Boolean TryGetValue(global::System.String key, out global::System.Object @value) { @value = default; return default; }
    public global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>> GetEnumerator() => default;
  }
  public enum RacingCameraAngle : int {
    Back = 0,
    Front = 1,
    Inside = 2,
  }
  public partial class SignedInEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.GamerServices.SignedInGamer Gamer { get => default; set { } }
    public SignedInEventArgs(global::Microsoft.Xna.Framework.GamerServices.SignedInGamer gamer) { }
  }
  public sealed partial class SignedInGamer : global::Microsoft.Xna.Framework.GamerServices.Gamer {
    public global::Microsoft.Xna.Framework.GamerServices.GameDefaults GameDefaults { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerPrivileges Privileges { get => default; set { } }
    public global::System.Int32 PartySize { get => default; set { } }
    public global::Microsoft.Xna.Framework.GamerServices.GamerPresence Presence { get => default; set { } }
    public static event global::System.EventHandler<global::Microsoft.Xna.Framework.GamerServices.SignedInEventArgs> SignedIn { add { } remove { } }
    public static event global::System.EventHandler<global::Microsoft.Xna.Framework.GamerServices.SignedOutEventArgs> SignedOut { add { } remove { } }
    public global::System.Boolean IsFriend(global::Microsoft.Xna.Framework.GamerServices.Gamer gamer) => default;
    public global::Microsoft.Xna.Framework.GamerServices.FriendCollection GetFriends() => new global::Microsoft.Xna.Framework.GamerServices.FriendCollection();
    public global::System.Boolean IsHeadset(global::Microsoft.Xna.Framework.Audio.Microphone microphone) => default;
    public global::System.IAsyncResult BeginAwardAchievement(global::System.String achievementKey, global::System.AsyncCallback callback, global::System.Object state) => default;
    public void EndAwardAchievement(global::System.IAsyncResult result) { }
    public void AwardAchievement(global::System.String achievementKey) { }
    public global::System.IAsyncResult BeginGetAchievements(global::System.AsyncCallback callback, global::System.Object asyncState) => default;
    public global::Microsoft.Xna.Framework.GamerServices.AchievementCollection EndGetAchievements(global::System.IAsyncResult result) => default;
    public global::Microsoft.Xna.Framework.GamerServices.AchievementCollection GetAchievements() => default;
  }
  public sealed partial class SignedInGamerCollection : global::Microsoft.Xna.Framework.GamerServices.GamerCollection<global::Microsoft.Xna.Framework.GamerServices.SignedInGamer> {
  }
  public partial class SignedOutEventArgs : global::System.EventArgs {
    public global::Microsoft.Xna.Framework.GamerServices.SignedInGamer Gamer { get => default; set { } }
    public SignedOutEventArgs(global::Microsoft.Xna.Framework.GamerServices.SignedInGamer gamer) { }
  }
}

